apiVersion: v1
kind: Service
metadata:
  name: my-app-2-svc
  labels:
   service: simple-express
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: simple-express
